name: Actions Labeller

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Label PR based on files changed
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true

      - name: Add additional labels
        if: github.event.action == 'opened'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-triage, review-requested"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
